version: '3.8'

services:
  voice_match:
    build: .
    container_name: voice_match_app
    ports:
      - "127.0.0.1:7861:7860"
    volumes:
      - ./logs:/app/logs
      - ./pretrained_models:/app/pretrained_models
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    restart: unless-stopped
